name: env-dc-swot-filtering
channels:
  - pyviz
dependencies:
  - python=3.10
  - numpy=1.21.*
  - scipy
  - hvplot
  - conda-forge::pyinterp
  - holoviews
  - anaconda::basemap
  - geoviews
  - cartopy
  - tabulate
  - datashader
  - netcdf4
